### ISSUE TITLE
Problem with the pro membership 

### ISSUE THREAD

**Issue by ataliba** [GitJournal/GitJournal#171]
## Environment

**App version:**    GitJournal 1.5.7+1438
**Device information:** 
 - OS name and version: Android 8.1 GO
 - Manufacturer: Multilaser
 - Model: M7S PLUS

## Description

I have an Android tablet and I needed to upgrade from Android 7.1.1 to 8.1. And the manufacturer's program cleans it all up to do this process.
With that I needed to reinstall all my applications. And one of them was GitJournal.
As I am already a Pro, I simply installed it and thought that by clicking on "Unlock Pro Version" the Pro would already be recognized. For some reason nothing happens and, when trying to purchase the Pro again, it warns me that I already have the subscription and releases the error

Purchase Failed
PurchaseErrorCode.productAlreadyPurchasedError

**Expected behavior:**

Pro Unlocked 

**Current behavior:**

Pro Locked 

## Steps to reproduce

1. Uninstall the app or reset the device to factory 
2. Reinstall the GitJournal 
3. Config 
4. Try to unlock the Pro if you have this enabled

**Comment by necopinus** [comment]
I’m experiencing a similar issue, except on iOS 13. After subscribing at the default tier (as some of the features I want to test out are “Pro”), the app fails to activate and continues to show the “Unlock Pro Version” prompts. I’ve now waited overnight in case there was a delay, but still no dice.

There were some potentially interesting debug messages last night where it looked like a purchase could be seen but then `IsPro` was reported as `false`, but I can’t duplicate these this morning; now, nothing is reported at all except that `proMode` is still `false` in the settings.

**Comment by necopinus** [comment]
At least on iOS, reinstalling has no effect, but attempting to change the subscription level results in the same error as the OP.

**Comment by vHanda** [comment]
I've managed to reproduce this. I'll fix it today! Sorry

**Comment by vHanda** [comment]
I haven't managed to figure out what is going on - could everyone affected please use the 'report a bug' button so that I can see the logs?

**Comment by necopinus** [comment]
For whatever reason, the **Bug Report** button isn’t working for me. However, here’s what looks to be the relevant section of the log from the **Debug App** section of the settings:

```
06:36:24 Got PurchaserInfo PurchaserInfo{entitlements: EntitlementInfos{all: {}, active: {}}, latestExpirationDate: null, allExpirationDates: {}, allPurchaseDates: {}, activeSubscriptions: [], allPurchasedProductIdentifiers: [], firstSeen: 2020-07-03T12:36:24Z, originalAppUserId: e0dd54f3-3aa4-4299-b954-31f614d5ef35, requestDate: 2020-07-03T12:36:24Z, originalApplicationVersion: null}
06:36:24 IsPro false
06:36:27 Got PurchaserInfo PurchaserInfo{entitlements: EntitlementInfos{all: {}, active: {}}, latestExpirationDate: null, allExpirationDates: {}, allPurchaseDates: {}, activeSubscriptions: [], allPurchasedProductIdentifiers: [], firstSeen: 2020-07-03T12:36:24Z, originalAppUserId: e0dd54f3-3aa4-4299-b954-31f614d5ef35, requestDate: 2020-07-03T12:36:24Z, originalApplicationVersion: null}
06:36:27 IsPro false
```

These lines are all contiguous for me; before them are some lines about setting up the note cache, and after them is when I reconnected the app with my GitHub repo (this was after I tried deleting and redownloading it, on the odd chance that the purchase might appear then).

Purchase does show up in the App Store.

![040010B3-E34F-4F78-9EDD-7AA71F4F0BC0](https://user-images.githubusercontent.com/134362/86489293-245f0980-bd21-11ea-9a17-ec3b70b374ce.png)

**Comment by vHanda** [comment]
Hi. I released a new version on Android - 1.58 - could someone please confirm if the fix works?

**Comment by ataliba** [comment]
Hey @vHanda 

Problem solved on Android.

**Comment by necopinus** [comment]
Problem still exists for me on iOS 1.59.3.

Would it help for me to cancel my subscription, wait until it expires (8/3), and then try resubscribing to see if I can get a better/different log snippet?

(Also, “Bug Report” still doesn’t work, but I’m now wondering if that’s because I don’t have the Mail app installed, or any system-level mail configured?)
