### ISSUE TITLE
Enabling "Store Repo Externally" does not work correctly (the selected directory is not used)

### ISSUE THREAD

**Issue by kankaristo** [GitJournal/GitJournal#377]
## Environment

**App version:**  1.73.2+2064
**Device information:**
 - OS name and version: Android 10
 - Manufacturer: Lenovo/Motorola
 - Model: Moto G 5G Plus

## Description

**Expected behavior:**
The app opens normally, or at least shows an error message.

**Current behavior:**
The app shows the loading screen (GitJournal logo on white background) and never goes forward.

## Steps to reproduce

1. Open a fresh install of the app
2. Enable "Store Repo Externally" in the settings
3. Close and re-open the app

## Others

I'm running the Google Play version, so I don't have logs, sorry.

The only way to successfully open the app again is to delete all app data (not just cache).

I'm not sure if "external" refers to an SD card or not. I don't have an SD card in my phone, but as far as I know, /storage/emulated/0 should point to internal storage (where I have my downloads folder, etc.). And in any case, the app should be able to recover from this.

**Comment by vHanda** [comment]
Hey. Could you please update to 1.73.6 and try again? It should fix the issue.

**Comment by kankaristo** [comment]
@vHanda, that seems to have partially fixed the issue, now the app opens again.

However, now I'm getting a bug similar to https://github.com/GitJournal/GitJournal/issues/347.

If I start with a fresh install of GitJournal:
1. Enable "Store Repo Externally"
2. Create a new empty folder and select it
3. Try setting up a Git host
4. Gives an error "Not a Git repository"

If I disable "Store Repo Externally", set up the Git host and then enable "Store Repo Externally", everything appears to work (i.e. no errors). However, the directory I chose remains empty, so GitJournal still seems to store files in the "internal" location (enabling "Store Repo Externally" has no effect).

**Comment by vHanda** [comment]
Hmm. What happens if you create a note before enabling Store Repo Externally? Is the note moved?

**Comment by vHanda** [comment]
(Also, if you ever want to see the logs they are visible from the Settings -> Debug App)

**Comment by kankaristo** [comment]
> Hmm. What happens if you create a note before enabling Store Repo Externally? Is the note moved?

No, the note isn't moved then either.

I just noticed that GitJournal sets the repo location to `/storage/emulated/0/Android/data/io.gitjournal/files/GitJournal/journal` and not to the directory that I created and selected/granted permissions for (`/storage/emulated/0/notes` in this case).


> (Also, if you ever want to see the logs they are visible from the Settings -> Debug App)

Ah, good to know, that wasn't available when the app froze on the loading screen. :stuck_out_tongue:

**Comment by vHanda** [comment]
Thanks for the additional info. Let me see what I can do.

**Comment by LecrisUT** [comment]
Hope a fix will be available soon. I am also experiencing this problem on android 10 aosp, and it is the limiting bug that stops me from using this app, until git https support is implemented.

**Comment by pigeonlips** [comment]
I found the same. I was on an old phone (running marshmallow) and had a todo.md that was in the /Android/data/io.gitjournal/files/ that i was sharing with todo.txt and this worked really well. My new phone, on android 11, doesnt seam to let me (or other apps) access anything in that folder anymore so was excited to try the store repo externally. 

When starting from fresh and selecting store repo externally and create a note nothing appears in the directory. 

after selecting "store repo externally" it doesnt seem to change the "repo location" and it remains pointing at `/Android/data/io.gitjournal/files/...` folder again rather than the one i originally selected. I'm not sure if thats expected.

heres a dump of the debug log 

```{"t":1611192112475,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------- App Launched ---------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112476,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192112477,"l":"i","msg":"AppSetting {onBoardingCompleted: false, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , pseudoId: f2f09d38-7859-4fb8-9897-73db2fa49cfa, debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false}","stack":"null "}
{"t":1611192112485,"l":"d","msg":"Event.AppUpdate","stack":"null "}
{"t":1611192112491,"l":"d","msg":"Analytics Collection: true","stack":"null "}
{"t":1611192112496,"l":"d","msg":"Event.Settings","stack":"null "}
{"t":1611192112496,"l":"i","msg":"Setting {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, customMetaData: , yamlHeaderEnabled: true, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, remoteSyncFrequency: automatic, showNoteSummary: true, folderViewHeaderType: TitleGenerated, version: 2, markdownDefaultView: Last Used, markdownLastUsedView: Edit, homeScreen: all_notes, imageLocationSpec: ., zenMode: false, saveTitleInH1: true, swipeToDelete: true, inlineTagPrefixes: #, emojiParser: true, folderName: journal, bottomMenuBar: true, confirmDelete: true, storeInternally: true, storageLocation: , sshPublicKey: false, sshPrivateKey: false}","stack":"null "}
{"t":1611192112497,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192112498,"l":"i","msg":"Calling GitInit for journal at: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192112520,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":"null "}
{"t":1611192112521,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false","stack":"null "}
{"t":1611192112523,"l":"i","msg":"Notes Cache Loaded: 0 items","stack":"null "}
{"t":1611192112523,"l":"i","msg":"Finished loading the notes cache","stack":"null "}
{"t":1611192112532,"l":"i","msg":"Notes Cache saving: 0 items","stack":"null "}
{"t":1611192112572,"l":"i","msg":"Finished loading all the notes","stack":"null "}
{"t":1611192112597,"l":"d","msg":"Received Share with App (text): null","stack":"null "}
{"t":1611192112624,"l":"d","msg":"Event.AppFirstOpen","stack":"null "}
{"t":1611192123009,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1611192139521,"l":"i","msg":"Moving repo to /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files","stack":"null "}
{"t":1611192139522,"l":"i","msg":"Old Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192139522,"l":"i","msg":"New Path: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192139548,"l":"i","msg":"Notes Cache saving: 0 items","stack":"null "}
{"t":1611192151867,"l":"d","msg":"Note modified - saving","stack":"null "}
{"t":1611192151868,"l":"d","msg":"Event.NoteAdded","stack":"null "}
{"t":1611192151888,"l":"d","msg":"Got addNote lock","stack":"null "}
{"t":1611192151910,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":"null "}
{"t":1611192154072,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1611192297359,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297360,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"--------- App Launched ---------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1611192297361,"l":"i","msg":"AppSetting {onBoardingCompleted: true, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , pseudoId: f2f09d38-7859-4fb8-9897-73db2fa49cfa, debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false}","stack":"null "}
{"t":1611192297372,"l":"d","msg":"Analytics Collection: true","stack":"null "}
{"t":1611192297376,"l":"d","msg":"Event.Settings","stack":"null "}
{"t":1611192297376,"l":"i","msg":"Setting {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, customMetaData: , yamlHeaderEnabled: true, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, remoteSyncFrequency: automatic, showNoteSummary: true, folderViewHeaderType: TitleGenerated, version: 2, markdownDefaultView: Last Used, markdownLastUsedView: Edit, homeScreen: all_notes, imageLocationSpec: ., zenMode: false, saveTitleInH1: true, swipeToDelete: true, inlineTagPrefixes: #, emojiParser: true, folderName: journal, bottomMenuBar: true, confirmDelete: true, storeInternally: false, storageLocation: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal, sshPublicKey: false, sshPrivateKey: false}","stack":"null "}
{"t":1611192297377,"l":"i","msg":"Loading Repo at path /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192297388,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":"null "}
{"t":1611192297390,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false","stack":"null "}
{"t":1611192297400,"l":"i","msg":"Notes Cache Loaded: 0 items","stack":"null "}
{"t":1611192297401,"l":"i","msg":"Finished loading the notes cache","stack":"null "}
{"t":1611192297481,"l":"i","msg":"Notes Cache saving: 1 items","stack":"null "}
{"t":1611192297485,"l":"i","msg":"Finished loading all the notes","stack":"null "}
{"t":1611192297501,"l":"d","msg":"Received Share with App (text): null","stack":"null "}
{"t":1611192304426,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1611192465458,"l":"i","msg":"Old Path: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192465459,"l":"i","msg":"New Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192465516,"l":"i","msg":"Notes Cache saving: 1 items","stack":"null "}
{"t":1611192474134,"l":"i","msg":"Moving repo to /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files","stack":"null "}
{"t":1611192474134,"l":"i","msg":"Old Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192474134,"l":"i","msg":"New Path: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192474198,"l":"i","msg":"Notes Cache saving: 1 items","stack":"null "}
{"t":1611192559623,"l":"i","msg":"No log file for 2021-01-20 14:29:19.622705","stack":"null "}
{"t":1611192656447,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1611192668627,"l":"i","msg":"Old Path: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192668627,"l":"i","msg":"New Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192668688,"l":"i","msg":"Notes Cache saving: 1 items","stack":"null "}
{"t":1611192677685,"l":"i","msg":"Moving repo to /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files","stack":"null "}
{"t":1611192677685,"l":"i","msg":"Old Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611192677685,"l":"i","msg":"New Path: /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal","stack":"null "}
{"t":1611192677738,"l":"i","msg":"Notes Cache saving: 1 items","stack":"null "}
{"t":1611192682686,"l":"i","msg":"No log file for 2021-01-20 14:31:22.685865","stack":"null "}```

The folder i tried to use isn't mentioned in the logs above as it was 'storage/emulated/0/notes'

hope it helps.

**Comment by pigeonlips** [comment]
if i go to set up github at this point i also get the  "Not a Git repository". Heres a dump of the logs again from that bit 

```{"t":1611193068285,"l":"d","msg":"Event.DrawerSetupGitHost","stack":"null "}
{"t":1611193069528,"l":"d","msg":"githostsetup_button_click GitHub","stack":"null "}
{"t":1611193069528,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1611193070777,"l":"d","msg":"githostsetup_button_click Setup Automatically","stack":"null "}
{"t":1611193070777,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1611193072139,"l":"d","msg":"githostsetup_button_click Authorize GitJournal","stack":"null "}
{"t":1611193072139,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1611193072139,"l":"d","msg":"Starting autoconfigure","stack":"null "}
{"t":1611193072140,"l":"d","msg":"GitHub: Installed Handler","stack":"null "}
{"t":1611193073418,"l":"d","msg":"GitHub: Called onUrl with {URL: gitjournal://login.oauth2?code=<retracted>}","stack":"null "}
{"t":1611193074100,"l":"d","msg":"GithubResponse: access_token=<retracted>&scope=repo&token_type=bearer","stack":"null "}
{"t":1611193074100,"l":"d","msg":"GitHost Initalized: GitHostType.GitHub","stack":"null "}
{"t":1611193074710,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1611193074743,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1611193078895,"l":"d","msg":"githostsetup_button_click Next","stack":"null "}
{"t":1611193078896,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1611193078896,"l":"d","msg":"Starting autoconfigure copletion","stack":"null "}
{"t":1611193078896,"l":"i","msg":"Generating SSH Key","stack":"null "}
{"t":1611193084450,"l":"i","msg":"Generating KeyPair took: 0:00:05.553757","stack":"null "}
{"t":1611193084451,"l":"d","msg":"Keys Dir: [/data/user/0/io.gitjournal.gitjournal/code_cache/keysYONBYB/id_rsa, /data/user/0/io.gitjournal.gitjournal/code_cache/keysYONBYB/id_rsa.pub]","stack":"null "}
{"t":1611193084462,"l":"i","msg":"Adding as a deploy key","stack":"null "}
{"t":1611193085108,"l":"d","msg":"GitHub addDeployKey: {\"id\":49562495,\"key\":\"<retracted but key looks good - is a valid one>",\"url\":\"https://api.github.com/repos/<retracted>/keys/<retracted>\",\"title\":\"GitJournal\",\"verified\":true,\"created_at\":\"2021-01-21T01:38:05Z\",\"read_only\":false}","stack":"null "}
{"t":1611193085109,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"null "}
{"t":1611193085111,"l":"e","msg":"Failed to add remote","ex":"Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"
package:dart_git/git.dart 63               
GitRepository.load package:gitjournal/setup/screens.dart 
528  GitHostSetupScreenState._startGitClone <asynchronous suspension> 
"}
{"t":1611193085112,"l":"i","msg":"Not completing gitClone because of error","stack":"null "}
{"t":1611193085112,"l":"d","msg":"Event.GitHostSetupGitCloneError","stack":"null "}
{"t":1611193095054,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1611193097934,"l":"e","msg":"Failed to remove remote","ex":"Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"
package:dart_git/git.dart 63               
GitRepository.load package:gitjournal/setup/screens.dart 419  
GitHostSetupScreenState._removeRemote <asynchronous suspension> 
"}
{"t":1611193097935,"l":"e","msg":"Got Exception","ex":"Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":"
package:dart_git/git.dart 63               
GitRepository.load package:gitjournal/setup/screens.dart 419  
GitHostSetupScreenState._removeRemote <asynchronous suspension> 
"}
{"t":1611193103552,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1611193108591,"l":"i","msg":"No log file for 2021-01-20 14:38:28.590786","stack":"null "}
```

**Comment by jy1263** [comment]
same issue

**Comment by MisterY** [comment]
More info in #428

**Comment by MisterY** [comment]
> hope it helps.
> ```

@pigeonlips, please use the template below to enclose long log listings:

```
<details>
  <summary>Logs</summary>

\```
16:38:52 Moving repo to /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files
16:38:52 FilePicker: Got /storage/emulated/0/sync/notes/org but it is not writable
16:38:52 ExtStorage: Got /storage/emulated/0 but it is not writable

</details>
```

**Comment by MisterY** [comment]
Done!

**Comment by jlamoure** [comment]
Gitjournal 1.75.0+2317

I allowed permission for Gitjournal to the folder "gitjournal" under my SD card, however it created a folder "GitJournal" under the internal storage path "/storage/emulated/0/GitJournal" and placed the repo there instead.
