### ISSUE TITLE
Infinity Cloning ...

### ISSUE THREAD

**Issue by maximmarakov** [GitJournal/GitJournal#417]
## Environment

**App version:** 1.73.10, latest available in appStore
**Device information:**
 - OS name and version: iOS 14.3,
 - Manufacturer: Apple inc.
 - Model: iPhone XS max

## Description
Infinity cloning in manual and auto add github repo

**Expected behavior:**
final process

**Current behavior:**
infinity process

## Steps to reproduce

1. setup host
2. github
3. any of "setup automatically" or "manually"
4. auth ok
5. select existing or create new repo
5.1. if new then creating ok ( existing in github)
6. cloning ...

## Others 
  

Images

<details>
  <summary>Logs</summary>

![image](https://user-images.githubusercontent.com/36736392/107844511-b7067180-6df5-11eb-9782-22d8c3e4e9aa.png)

```
```

sorry, i'm a teapot :sweat_smile: 

```
```
</details>

**Comment by maximmarakov** [comment]
:thinking: with GitLab it works ok. Apparently trouble only with GitHub.

**Comment by vHanda** [comment]
Could you please restart the app after it gets stuck and then copy the logs from setting -> debug.

**Comment by maximmarakov** [comment]
:thinking: it works in the evening. Maybe it was temporary trouble.

**Comment by vHanda** [comment]
Oh man. Could you please send me the debug logs? Or see if you notice anything strange.

**Comment by maximmarakov** [comment]
So i reproduced error. It happens if i install app, trying add GitHub repo -> infinity cloning. BUT if i re-open GitJournal, i saw that all repo was successfully cloned. But git was dropped. Then i re-add same repo and all will be OK.
 
Logs: 
{"t":1613227442591,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442591,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"--------- App Launched ---------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227442592,"l":"i","msg":"AppSetting {onBoardingCompleted: false, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , pseudoId: ef3362cc-efd7-47ef-b602-d35d287b1679, debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false}","stack":"null "}
{"t":1613227442594,"l":"d","msg":"Analytics Collection: true","stack":"null "}
{"t":1613227442594,"l":"d","msg":"Event.AppUpdate","stack":"null "}
{"t":1613227442622,"l":"d","msg":"Event.Settings","stack":"null "}
{"t":1613227442622,"l":"i","msg":"Setting {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, customMetaData: , yamlHeaderEnabled: true, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, remoteSyncFrequency: automatic, showNoteSummary: true, folderViewHeaderType: TitleGenerated, version: 2, markdownDefaultView: Last Used, markdownLastUsedView: Edit, homeScreen: all_notes, imageLocationSpec: ., zenMode: false, saveTitleInH1: true, swipeToDelete: true, inlineTagPrefixes: #, emojiParser: true, folderName: journal, bottomMenuBar: true, confirmDelete: true, storeInternally: true, storageLocation: , sshPublicKey: false, sshPrivateKey: false}","stack":"null "}
{"t":1613227442623,"l":"i","msg":"Loading Repo at path /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227442623,"l":"i","msg":"Calling GitInit for journal at: /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227442631,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":"null "}
{"t":1613227442631,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false","stack":"null "}
{"t":1613227442632,"l":"i","msg":"Notes Cache Loaded: 0 items","stack":"null "}
{"t":1613227442632,"l":"i","msg":"Finished loading the notes cache","stack":"null "}
{"t":1613227442632,"l":"i","msg":"Old Transactions: 0","stack":"null "}
{"t":1613227442638,"l":"i","msg":"Notes Cache saving: 0 items","stack":"null "}
{"t":1613227442644,"l":"i","msg":"Finished loading all the notes","stack":"null "}
{"t":1613227442659,"l":"d","msg":"Received Share with App (text): null","stack":"null "}
{"t":1613227442678,"l":"d","msg":"Event.AppFirstOpen","stack":"null "}
{"t":1613227451254,"l":"d","msg":"Event.DrawerSetupGitHost","stack":"null "}
{"t":1613227452152,"l":"d","msg":"githostsetup_button_click GitHub","stack":"null "}
{"t":1613227452153,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227453336,"l":"d","msg":"githostsetup_button_click Setup Automatically","stack":"null "}
{"t":1613227453337,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227454310,"l":"d","msg":"githostsetup_button_click Authorize GitJournal","stack":"null "}
{"t":1613227454310,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227454310,"l":"d","msg":"Starting autoconfigure","stack":"null "}
{"t":1613227454311,"l":"d","msg":"GitHub: Installed Handler","stack":"null "}
{"t":1613227459730,"l":"d","msg":"GitHub: Called onUrl with {URL: gitjournal://login.oauth2?code=some code}","stack":"null "}
{"t":1613227460244,"l":"d","msg":"GithubResponse: access_token=some access token&scope=repo&token_type=bearer","stack":"null "}
{"t":1613227460244,"l":"d","msg":"GitHost Initalized: GitHostType.GitHub","stack":"null "}
{"t":1613227460737,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1613227460753,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1613227464789,"l":"d","msg":"githostsetup_button_click Next","stack":"null "}
{"t":1613227464789,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227464790,"l":"d","msg":"Starting autoconfigure copletion","stack":"null "}
{"t":1613227464790,"l":"i","msg":"Generating SSH Key","stack":"null "}
{"t":1613227466620,"l":"i","msg":"Generating KeyPair took: 0:00:01.830020","stack":"null "}
{"t":1613227466621,"l":"d","msg":"Keys Dir: [/private/var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/tmp/keysTget4w/id_rsa, /private/var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/tmp/keysTget4w/id_rsa.pub]","stack":"null "}
{"t":1613227466621,"l":"i","msg":"Adding as a deploy key","stack":"null "}
{"t":1613227467406,"l":"d","msg":"GitHub addDeployKey: {\"id\":50268750,\"key\":\"ssh-rsa some key ",\"url\":\"https://api.github.com/repos/maximmarakov/zettelkasten/keys/50268750\",\"title\":\"GitJournal\",\"verified\":true,\"created_at\":\"2021-02-13T14:44:27Z\",\"read_only\":false}","stack":"null "}
{"t":1613227467407,"l":"i","msg":"RepoPath: /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227471479,"l":"i","msg":"Got default branch: master","stack":"null "}
{"t":1613227471479,"l":"i","msg":"Using remote branch: master","stack":"null "}
{"t":1613227471484,"l":"i","msg":"Completing - no local branch","stack":"null "}
{"t":1613227518077,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1613227524809,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1613227528374,"l":"i","msg":"No log file for 2021-02-12 19:45:28.374051","stack":"null "}
{"t":1613227579219,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------- App Launched ---------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"--------------------------------","stack":"null "}
{"t":1613227579220,"l":"i","msg":"AppSetting {onBoardingCompleted: true, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , pseudoId: ef3362cc-efd7-47ef-b602-d35d287b1679, debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false}","stack":"null "}
{"t":1613227579222,"l":"d","msg":"Analytics Collection: true","stack":"null "}
{"t":1613227579223,"l":"d","msg":"Event.Settings","stack":"null "}
{"t":1613227579223,"l":"i","msg":"Setting {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, customMetaData: , yamlHeaderEnabled: true, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, remoteSyncFrequency: automatic, showNoteSummary: true, folderViewHeaderType: TitleGenerated, version: 2, markdownDefaultView: Last Used, markdownLastUsedView: Edit, homeScreen: all_notes, imageLocationSpec: ., zenMode: false, saveTitleInH1: true, swipeToDelete: true, inlineTagPrefixes: #, emojiParser: true, folderName: journal, bottomMenuBar: true, confirmDelete: true, storeInternally: true, storageLocation: , sshPublicKey: true, sshPrivateKey: true}","stack":"null "}
{"t":1613227579223,"l":"i","msg":"Loading Repo at path /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227579224,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":"null "}
{"t":1613227579225,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false","stack":"null "}
{"t":1613227579225,"l":"i","msg":"Old Transactions: 0","stack":"null "}
{"t":1613227579227,"l":"i","msg":"Notes Cache Loaded: 0 items","stack":"null "}
{"t":1613227579227,"l":"i","msg":"Finished loading the notes cache","stack":"null "}
{"t":1613227579249,"l":"d","msg":"Received Share with App (text): null","stack":"null "}
{"t":1613227579266,"l":"i","msg":"Notes Cache saving: 20 items","stack":"null "}
{"t":1613227579268,"l":"i","msg":"Finished loading all the notes","stack":"null "}
{"t":1613227583763,"l":"d","msg":"Event.DrawerSetupGitHost","stack":"null "}
{"t":1613227584610,"l":"d","msg":"githostsetup_button_click GitHub","stack":"null "}
{"t":1613227584610,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227586610,"l":"d","msg":"githostsetup_button_click Setup Automatically","stack":"null "}
{"t":1613227586611,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227587465,"l":"d","msg":"githostsetup_button_click Authorize GitJournal","stack":"null "}
{"t":1613227587465,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227587465,"l":"d","msg":"Starting autoconfigure","stack":"null "}
{"t":1613227587465,"l":"d","msg":"GitHub: Installed Handler","stack":"null "}
{"t":1613227588279,"l":"d","msg":"GitHub: Called onUrl with {URL: gitjournal://login.oauth2?code=some code}","stack":"null "}
{"t":1613227588775,"l":"d","msg":"GithubResponse: access_token=dome access token&scope=repo&token_type=bearer","stack":"null "}
{"t":1613227588776,"l":"d","msg":"GitHost Initalized: GitHostType.GitHub","stack":"null "}
{"t":1613227589314,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1613227589327,"l":"d","msg":"Starting RepoSelector","stack":"null "}
{"t":1613227592994,"l":"d","msg":"githostsetup_button_click Next","stack":"null "}
{"t":1613227592995,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":"null "}
{"t":1613227592995,"l":"d","msg":"Starting autoconfigure copletion","stack":"null "}
{"t":1613227592996,"l":"i","msg":"Generating SSH Key","stack":"null "}
{"t":1613227594598,"l":"i","msg":"Generating KeyPair took: 0:00:01.602032","stack":"null "}
{"t":1613227594598,"l":"d","msg":"Keys Dir: [/private/var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/tmp/keysDQqPiw/id_rsa, /private/var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/tmp/keysDQqPiw/id_rsa.pub]","stack":"null "}
{"t":1613227594599,"l":"i","msg":"Adding as a deploy key","stack":"null "}
{"t":1613227595610,"l":"d","msg":"GitHub addDeployKey: {\"id\":50268778,\"key\":\"ssh-rsa some key",\"url\":\"https://api.github.com/repos/maximmarakov/zettelkasten/keys/50268778\",\"title\":\"GitJournal\",\"verified\":true,\"created_at\":\"2021-02-13T14:46:35Z\",\"read_only\":false}","stack":"null "}
{"t":1613227595612,"l":"i","msg":"RepoPath: /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227599402,"l":"i","msg":"Got default branch: master","stack":"null "}
{"t":1613227599402,"l":"i","msg":"Using remote branch: master","stack":"null "}
{"t":1613227599410,"l":"i","msg":"Completing - localBranch: master","stack":"null "}
{"t":1613227599428,"l":"d","msg":"Event.GitHostSetupComplete","stack":"null "}
{"t":1613227599429,"l":"i","msg":"completeGitHostSetup repoPath: /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Documents/journal","stack":"null "}
{"t":1613227599447,"l":"d","msg":"Event.RepoSynced","stack":"null "}
{"t":1613227599484,"l":"i","msg":"Notes Cache saving: 20 items","stack":"null "}
{"t":1613227601373,"l":"i","msg":"Notes Cache saving: 20 items","stack":"null "}
{"t":1613227601375,"l":"d","msg":"Synced!","stack":"null "}
{"t":1613227607513,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1613227654715,"l":"i","msg":"Log file /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Library/Caches/logs/2021-02-12.jsonl not found","stack":"null "}
{"t":1613227655532,"l":"i","msg":"Log file /var/mobile/Containers/Data/Application/11EBAFB4-1805-432C-899F-A9D28763511D/Library/Caches/logs/2021-02-12.jsonl not found","stack":"null "}
{"t":1613227655899,"l":"d","msg":"Event.DrawerSettings","stack":"null "}
{"t":1613227658781,"l":"i","msg":"No log file for 2021-02-12 19:47:38.781306","stack":"null "}

**Comment by vHanda** [comment]
Weird. I can't seem to reproduce it. Could you please tell me repo name? It already existed, right?

**Comment by maximmarakov** [comment]
repo name is maximmarakov/zettelkasten, but it does not matter. It happens also with clear repo

**Comment by mnchrm** [comment]
I'm having this exact same issue with my zettlekasten, but maxim's temporary solution didn't work for me, if i close and then reopen the app, the notes are there, but they won't sync with git.

**Comment by dmelichar** [comment]
Same issue, same solution.

```
App version: 1.73.10
OS name and version: iOS 14.4
Manufacturer: Apple inc.
Model: iPhone SE
```

**Comment by vHanda** [comment]
I think this is fixed with `1.74`. Please let me know if it isn't and I'll reopen it, and put it on top of my todo list.

**Comment by mnchrm** [comment]
> 
> 
> I think this is fixed with `1.74`. Please let me know if it isn't and I'll reopen it, and put it on top of my todo list.

Unfortunately it hasn't fixed the issue for me... i'm still having the issue with infinity cloning.

**Comment by vHanda** [comment]
@mnchrm : Could you please paste your debug logs? I've added extra information.

**Comment by vHanda** [comment]
Please let me know if anyone if still having this issue.
