### ISSUE TITLE
Not loading all notes, existing repo can't sync, can't set new external storage location 

### ISSUE THREAD

**Issue by v21** [GitJournal/GitJournal#575]
Opened up GitJournal after the update to 1.82.1, and my existing repo was unable to find some notes (approximately half of them). Upon trying to sync, it showed an error saying that one of the git internal files was not writable.

Trying to recreate the notes repo, every time I select external storage it says that the directory is not writeable. Syncing just from git does work (this isn't especially useful for me, as I use Syncthing to sync with other devices, and just use git as a backup solution)

Tried setting up the dev build from F-Store, same deal.

Checking file permissions on the notes folder with Material Files, and they don't say anything weird - group is "everybody" and permissions are 0770. 

I cannot copy logs here - it says "Copied logs" but can't paste. If it's relevant, even after quitting the app, the logs still go back to the first open since the update - they are now quite large.

**Comment by v21** [comment]
more details: I'm on Android 11 (qssi-user 11 RKQ1.200903.002 V12.0.14.0.RFQEUXM) 

I can set an external directory successfully when I downgrade to GitJournal 1.80.0+2929. Although attempting to set a Github repo fails - it hangs on Loading... - debug logs say:

09:44:30 Uncaught Exception
         type '_GrowableList<dynamic>' is not a subtype of type 'List<String>'
           GitHub.repoFromJson                                   - gitjournal/apis/github.dart 280
           GitHub.listRepos.<fn>                                 - gitjournal/apis/github.dart 120
           _GrowableList.forEach                                 - dart:core

**Comment by noclueoncoding** [comment]
+1
I have exactly the same experience and usecase. Tested on Samsung Galaxy S10e and Galaxy Note10. Both on Android 11. Thanks for looking into it.

**Comment by vHanda** [comment]
My phone + tablet are still on Android 10, and I've mostly just tested out Android 11 on an emulator. I think GitJournal needs a new manage storage permission, but when I tried to add it in mid Oct, Google blacklisted GitJournal and I couldn't push any updates for 2 months. All my appeals went into a black hole. So I'm not keen on trying to add that permission again.

Possible way forward -
* I buy a more modern phone so I can properly test out Android 11 + future. And/or put Lineage OS on my current phone.
* I'll try to test things once more with an emulator, there might be a way to work around this 
* if in the end, GitJournal really needs that permission then I can maybe only put it in the FDroid version and inform users.

I'll keep you guys updated.

**Comment by vHanda** [comment]
I spent a lot of time looking into this today, and on an emulator I just cannot get it to write to the specified external storage directory without the extra `MANAGE_EXTERNAL_STORAGE` permission, which I cannot add. It does however write to the external storage, but not to the location you specified.

Next Steps -
* Release builds on F-Droid with the extra permission
* I'll start preparing a full proposal, including a video requesting GitJournal be given access.

@v21 @noclueoncoding : Could you both confirm that you only encounter this bug while using External Storage, and GitJournal works correctly with the internal storage?

**Comment by noclueoncoding** [comment]
On my side it always uses internal storage (/storage/emulated/0/Android/data/io.gitjournal.gitjournal/files ...) regardless of what i choose since any other path is "not writanble". After I found out I tried to move my repo to the internal path and sync it from there but I CRUD changes I make on the within the internal path but outside of the GitJournal app aren't recognized. Thus syncing via syncthing does not work for me.

**Comment by vHanda** [comment]
> On my side with 1.82 versions it always uses internal storage (/storage/emulated/0/Android/data/io.gitjournal.gitjournal/files ...) regardless of what i choose since any other path is "not writanble". After I found out I tried to move my repo to the internal path and sync it. Zhe repo gets recognized and I can see all my notes in the app. But when I make CRUD changes directly on the file system and outside of the GitJournal app those changes aren't recognized. Thus syncing via syncthing does not work for me.

Right. GitJournal doesn't yet detect changes done by other apps on startup. A workaround is to edit/add a new note and all the changes made by other apps will be committed.

**Comment by noclueoncoding** [comment]
> > On my side with 1.82 versions it always uses internal storage (/storage/emulated/0/Android/data/io.gitjournal.gitjournal/files ...) regardless of what i choose since any other path is "not writanble". After I found out I tried to move my repo to the internal path and sync it. Zhe repo gets recognized and I can see all my notes in the app. But when I make CRUD changes directly on the file system and outside of the GitJournal app those changes aren't recognized. Thus syncing via syncthing does not work for me.
> 
> Right. GitJournal doesn't yet detect changes done by other apps on startup. A workaround is to edit/add a new note and all the changes made by other apps will be committed.

With 1.80.0+2929 this works fine without the workaround (tested on externally stored repo only) I only have to restart the app. Of course a refresh by pulling down from the top would be even more convenient ;)

**Comment by vHanda** [comment]
> 
> With 1.80.0+2929 this works fine without the workaround (tested on externally stored repo only) I only have to restart the app. Of course a refresh by pulling down from the top would be even more convenient ;)

Fixed with `1.82.4`.

It will now auto-commit on load and when pressing the cloud button (or pulling down). And no notes should be missing.

**Comment by noclueoncoding** [comment]
Sorry but 1.82.4 still doesn't work with regard to storing the repo externally. Now when I flick the switch he doesn't complain that the chosen folder is not writable but still disregards my choice and puts the repo in /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files

**Comment by noclueoncoding** [comment]
On a positive note this version now recognizes changes made solely on the filesystem thus is now able to sync via syncthing. Btw. I still have to restart the app in order to see the changes. Pulling down doesn't seem to work.

**Comment by vHanda** [comment]
External storage is quite broken on Android 11+. I'm still figuring out the way to move forward.

Closing this in favor of https://github.com/GitJournal/GitJournal/issues/646
