### ISSUE TITLE
Saving new note can create duplicate files

### ISSUE THREAD

**Issue by patrick-boatner** [GitJournal/GitJournal#638]
This seems to happen 100% of the time I test this out. 

GitJournal 1.85.0+3575. Pixel 3a, Android 10.

Steps to reproduce:
* ~Probably need this setting turned on: Settings > Storage and File Formats > New Note Filename, set this to "Title".~
* Tap + to create a new note.
* The editor appears. ~I have the Markdown Editor chosen.~
* Type in a title and a note body
* Press android's home button. ~Open another app.~
* Open android's Recents screen. (Swipe up on newer phones, or the square/rectangle nav bar button on older phones)
* Find GitJournal and tap to open it back up.
* Tap the check mark (top left) to save the note.

**Expected behavior:** 
It only saves 1 copy of the note.

**Actual behavior:** 
It saves 2 copies of the note. One copy has the expected filename, like `Test title.md`. The other file is named `2022-06-24-07-36-51.md`

If it helps with troubleshooting, the 2 notes have almost the same content. The iso-ish filename note has this meta:
```
created: 2022-06-24T07:36:51-05:00
modified: 2022-06-24T07:36:51-05:00
```

but the filename note has this meta:
```
created: 2022-06-24T07:36:51-05:00
modified: 2022-06-24T07:37:07-05:00
```

**Comment by vHanda** [comment]
Confirmed. I can reliably reproduce it, and I know why it's happening.

**Comment by vHanda** [comment]
Could you please try and reproduce it with version `1.85`. I think it should now be fixed.

**Comment by locofocos** [comment]
Hey, I was trying to confirm that this has been fixed. I don't see any updates on the Google play store, nor any way to download nightly builds or releases here on Github. I'm already on 1.85, is that a typo?

Just LMK if you'd like me to test some build, happy to do that. Thanks for the fix!

**Comment by locofocos** [comment]
Hey, I just tested with version 1.85.2+3617 and I'm still seeing the issue. We should probably re-open the ticket.
